name: Medex Scraper

on:
  workflow_dispatch:

jobs:

  scrape:

    strategy:
      fail-fast: false

      matrix:
        batch:
          - [9000,9300]
          - [9300,9600]
          - [9600,9900]
          - [9900,10200]
          - [10200,10500]
          - [10500,10800]
          - [10800,11100]
          - [11100,11400]
          - [11400,11700]
          - [11700,12000]

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: browser-actions/setup-chrome@v1

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          python scripts/scrape.py \
          ${{ matrix.batch[0] }} \
          ${{ matrix.batch[1] }}

      - name: Upload Excel
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.batch[0] }}
          path: data/output/
