name: Medex Scraper

on:
  workflow_dispatch:

jobs:

  scrape:

    strategy:
      fail-fast: false

      matrix:
        batch:
          - [12000,12300]
          - [12300,12600]
          - [12600,12900]
          - [12900,13200]
          - [13200,13500]
          - [13500,13800]
          - [13800,14100]
          - [14100,14400]
          - [14400,14700]
          - [14700,15000]

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: browser-actions/setup-chrome@v1

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          python scripts/scrape.py \
          ${{ matrix.batch[0] }} \
          ${{ matrix.batch[1] }}

      - name: Upload Excel
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.batch[0] }}
          path: data/output/
