name: Medex Scraper

on:
  workflow_dispatch:

jobs:

  scrape:

    strategy:
      fail-fast: false

      matrix:
        batch:
          - [3000,3300]
          - [3300,3600]
          - [3600,3900]
          - [3900,4200]
          - [4200,4500]
          - [4500,4800]
          - [4800,5100]
          - [5100,5400]
          - [5400,5700]
          - [5700,6000]

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: browser-actions/setup-chrome@v1

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          python scripts/scrape.py \
          ${{ matrix.batch[0] }} \
          ${{ matrix.batch[1] }}

      - name: Upload Excel
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.batch[0] }}
          path: data/output/
